# Generated by Django 4.2.6 on 2023-10-22 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date',
        ),
        migrations.RemoveField(
            model_name='feedbacklink',
            name='feedbacks',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedbacklink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.feedbacklink'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='feedbacklink',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedbacklink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
    ]
