# Generated by Django 4.2.6 on 2023-10-22 05:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_feedback_date_remove_feedbacklink_feedbacks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedbacklink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.feedbacklink'),
        ),
        migrations.AlterField(
            model_name='feedbacklink',
            name='link',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
