# Generated by Django 4.2.6 on 2023-10-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_feedback_feedbacklink_alter_feedbacklink_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacklink',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbacklink',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
